spring:
  config:
    import: optional:file:.env[.properties]
  application:
    name: back

  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}

  output:
    ansi:
      enabled: always

  jpa:
    properties:
      hibernate:
        use_sql_comments: true
        format_sql: true
        highlight_sql: true

# JWT 공통 설정 (환경별로 기본값 제공)
custom:
  jwt:
    secretKey: ${JWT_SECRET_KEY:defaultSecretKeyForDevelopment1234567890}
    accessToken:
      expirationSeconds: ${JWT_EXPIRATION_SECONDS:3600}

# OAuth2 쿠키 설정 기본값
app:
  oauth2:
    cookie-domain: ${OAUTH2_COOKIE_DOMAIN:}
  cookie:
    same-site: Lax
    secure: true
    domain: ""
    max-age-seconds: 31536000

