spring:
  application:
    name: back
  profiles:
    active: test
  mvc:
    problem_details:
      enabled: true
  output:
    ansi:
      enabled: always
  datasource:
    hikari:
      auto-commit: false
  thymeleaf:
    cache: false
    prefix: file:src/main/resources/templates/
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        use_sql_comments: true
        format_sql: true
        highlight_sql: true
logging:
  level:
    org.hibernate.orm.jdbc.bind: TRACE
    org.hibernate.orm.jdbc.extract: TRACE
    org.springframework.transaction.interceptor: TRACE


