name: CI‑Test

on:
  push:                      # 브랜치에 푸시될 때마다
    branches: [ "*" ]        # → 모든 브랜치, 또는 'feature/**' 등 패턴 지정
  pull_request:              # PR 올라오면 한 번 더 보증
    branches: [ main, develop ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # 1. 소스 체크아웃
      - uses: actions/checkout@v4

      # 2. JDK 설치 (+ Gradle 캐시 자동 활성화)
      - name: Set up JDK 21
        uses: actions/setup-java@v4          # 최신 버전(현재 v4.7.1) :contentReference[oaicite:0]{index=0}
        with:
          java-version: '21'
          distribution: 'temurin'            # Eclipse Temurin LTS
          cache: gradle                      # 의존성 캐싱

      # 3. 테스트 실행
      - name: Run unit & integration tests
        run: ./gradlew clean test            # build.gradle.kts 그대로 사용

      # 4. (선택) 테스트 리포트 업로드
      - name: Upload Test Reports
        if: success() || failure()           # 실패해도 보고서 남기기
        uses: actions/upload-artifact@v4
        with:
          name: test-reports
          path: build/reports/tests/test     # JUnit HTML 보고서
