name: CI‑Test

on:
  push:
    branches: ["**"]
  pull_request:
    branches: [ main, develop ]
  workflow_dispatch:

jobs:
  tests:
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest, windows-latest ]
        include:
          - os: ubuntu-latest
            gradle_cmd: "./gradlew"
            report_path: "backend/build/reports/tests"
            domain_tasks: "testUser testExchange testTrade_log testWallet testCoin"

          - os: windows-latest
            gradle_cmd: ".\\gradlew.bat"
            report_path: "backend\\build\\reports\\tests"
            domain_tasks: "testUser testExchange testTrade_log testWallet testCoin"

    runs-on: ${{ matrix.os }}

    env:
      JWT_SECRET_KEY: ${{ secrets.JWT_SECRET_KEY }}
      GOOGLE_CLIENT_ID: ${{ secrets.GOOGLE_CLIENT_ID }}
      GOOGLE_CLIENT_SECRET: ${{ secrets.GOOGLE_CLIENT_SECRET }}
      REDIS_PORT: ${{ secrets.REDIS_PORT }}
      REDIS_HOST: ${{ secrets.REDIS_HOST }}

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: gradle

      # Ubuntu에서는 services.redis로 자동 실행
      - name: Set up Redis on Ubuntu
        if: matrix.os == 'ubuntu-latest'
        uses: supercharge/redis-github-action@1.2.0

      # Windows는 수동으로 redis 다운로드 후 실행
      - name: Install Redis on Windows
        if: matrix.os == 'windows-latest'
        shell: pwsh
        run: |
          $url = "https://raw.githubusercontent.com/ServiceStack/redis-windows/master/downloads/redis-64.3.0.503.zip"
          Invoke-WebRequest -Uri $url -OutFile redis.zip
          Expand-Archive redis.zip -DestinationPath redis
          Start-Process -FilePath redis\\redis-server.exe

      - name: Grant execute permission to gradlew.bat
        if: matrix.os == 'windows-latest'
        shell: pwsh
        run: icacls backend\\gradlew.bat /grant Everyone:RX

      - name: Run unit, integration, and domain tests
        run: ${{ matrix.gradle_cmd }} clean test integrationTest ${{ matrix.domain_tasks }}
        working-directory: backend

      - name: Upload Test Reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-reports-${{ matrix.os }}
          path: ${{ matrix.report_path }}
          retention-days: 7
