name: CI‑Test

on:
  push:
    branches: ["**"]
  pull_request:
    branches: [ main, develop ]
  workflow_dispatch:

jobs:
  tests:
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest, windows-latest ]
        include:
          - os: ubuntu-latest
            gradle_cmd: "./gradlew"
            report_path: "backend/build/reports/tests"
            domain_tasks: "testUser testExchange testTrade_log testWallet testCoin"
            needs_redis: true

          - os: windows-latest
            gradle_cmd: ".\\gradlew.bat"
            report_path: "backend\\build\\reports\\tests"
            domain_tasks: "testUser testExchange testTrade_log testWallet testCoin"
            needs_redis: true

    runs-on: ${{ matrix.os }}

    env:
      JWT_SECRET_KEY: ${{ secrets.JWT_SECRET_KEY }}
      GOOGLE_CLIENT_ID: ${{ secrets.GOOGLE_CLIENT_ID }}
      GOOGLE_CLIENT_SECRET: ${{ secrets.GOOGLE_CLIENT_SECRET }}
      REDIS_PORT: 6379
      REDIS_HOST: localhost

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: gradle

      # ✅ Windows용 Redis 설치 및 백그라운드 실행
      - name: Install and run Redis on Windows
        if: matrix.os == 'windows-latest' && matrix.needs_redis
        shell: pwsh
        run: |
          choco install redis-64 -y
          Start-Process "redis-server"

      # ✅ Linux용 Redis 서비스 (기존처럼 유지)
      - name: Set up Redis on Ubuntu
        if: matrix.os == 'ubuntu-latest' && matrix.needs_redis
        uses: docker://redis:7.0

      - name: Grant execute permission to gradlew.bat
        if: matrix.os == 'windows-latest'
        run: icacls backend\\gradlew.bat /grant Everyone:RX
        shell: pwsh

      - name: Run unit, integration, and domain tests
        run: ${{ matrix.gradle_cmd }} clean test integrationTest ${{ matrix.domain_tasks }}
        working-directory: backend

      - name: Upload Test Reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-reports-${{ matrix.os }}
          path: ${{ matrix.report_path }}
          retention-days: 7